### Change these!!
GenomeSize: 5000000
ShortreadCoverage: 56

ShortReadDirectory: /home/participant/cpang19/day4/MHC/TrioData/illumina/
# NOTE: short read endings MUST be .fq or .fa instead of .fastq or .fasta
# gzip is allowed
ShortReads:
- HG00514.fa


LongReadDirectory: /home/participant/cpang19/day4/MHC/TrioData/pacbio/
LongReads:
- HG00514.fa


TempDirectory: tmp/
OutputDirectory: output4/

# https://github.com/maickrau/GraphAligner
GraphAlignerPath: GraphAligner
# https://github.com/GATB/bcalm
BcalmPath: bcalm
# https://github.com/GATB/bcalm/blob/master/scripts/convertToGFA.py

BcalmConvertPath: ./convertToGFA.py
# https://github.com/mourisl/Lighter
LighterPath: lighter


### Misc params. Defaults might work

# k for error correcting the reads. Try between 10-30
SmallK: 23
# k for the de Bruijn graph. Try between ~1/2 and ~2/3 of short read length
BigK: 63
# minimum k-mer abundance for the de Bruijn graph. Try between 1/100 to 2/100 of short read coverage, but not below 2.
Abundance: 3
